// <auto-generated />
namespace Magazine.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addednameforstoreentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addednameforstoreentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201704141805158_added-name-for-store-entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
