// <auto-generated />
namespace Magazine.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeddependenciesforentities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddependenciesforentities));
        
        string IMigrationMetadata.Id
        {
            get { return "201704141651338_added-dependencies-for-entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
